<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\Branch;
use App\Models\Area;

class ErbilAreasSeeder extends Seeder
{
    public function run(): void
    {
        $this->command->info('🌍 Seeding Erbil areas from Excel data...');

        $erbil = Branch::where('city_name_en', 'Erbil')->firstOrFail();

        $areas = [
            ['area_name_en' => 'Marina 1', 'area_name_ar' => 'مارينا 1', 'area_name_ku' => 'مارینا 1'],
            ['area_name_en' => 'Sarbasti 4', 'area_name_ar' => 'سربستي 4', 'area_name_ku' => 'سەربەستی 4'],
            ['area_name_en' => '100 Meter Road', 'area_name_ar' => 'طريق 100 متر', 'area_name_ku' => '100 مەتر'],
            ['area_name_en' => '120 Meter Road', 'area_name_ar' => 'طريق 120 متر', 'area_name_ku' => '120 مەتر'],
            ['area_name_en' => '150 Meter Road', 'area_name_ar' => 'طريق 150 متر', 'area_name_ku' => '150 مەتر'],
            ['area_name_en' => '40 Meter Road', 'area_name_ar' => 'طريق 40 متر', 'area_name_ku' => '40 مەتر'],
            ['area_name_en' => '60 Meter Road', 'area_name_ar' => 'طريق 60 متر', 'area_name_ku' => '60 مەتر'],
            ['area_name_en' => '8 Hasarok', 'area_name_ar' => '٨ـي حصاروك', 'area_name_ku' => '٨ـی حەسارۆک'],
            ['area_name_en' => 'Ala', 'area_name_ar' => 'آلا', 'area_name_ku' => 'ئاڵا'],
            ['area_name_en' => 'Ala City', 'area_name_ar' => 'الا سيتي', 'area_name_ku' => 'ئاڵا سیتی'],
            ['area_name_en' => 'Almani City', 'area_name_ar' => 'ألماني سيتي', 'area_name_ku' => 'ئەڵمانی سیتی'],
            ['area_name_en' => 'Andazyaran', 'area_name_ar' => 'أندازياران', 'area_name_ku' => 'ئەندازیاران'],
            ['area_name_en' => 'Andazyaran City', 'area_name_ar' => 'أندازياران سيتي', 'area_name_ku' => 'ئەندازیاران سیتی'],
            ['area_name_en' => 'Ankawa', 'area_name_ar' => 'عنكاوة', 'area_name_ku' => 'عەنکاوە'],
            ['area_name_en' => 'Arab', 'area_name_ar' => 'عرب', 'area_name_ku' => 'عەرەب'],
            ['area_name_en' => 'Arab Kend', 'area_name_ar' => 'عرب كند', 'area_name_ku' => 'عارەب کەند'],
            ['area_name_en' => 'Arabi Nwe', 'area_name_ar' => 'عربی نوي', 'area_name_ku' => 'عارەبی نوێ'],
            ['area_name_en' => 'Aram City', 'area_name_ar' => 'مدينة آرام', 'area_name_ku' => 'شاری ئارام'],
            ['area_name_en' => 'Aras', 'area_name_ar' => 'اراس', 'area_name_ku' => 'ئاراس'],
            ['area_name_en' => 'Ari', 'area_name_ar' => 'آري', 'area_name_ku' => 'ئاری'],
            ['area_name_en' => 'Ashti City', 'area_name_ar' => 'آشتی سيتي', 'area_name_ku' => 'ئاشتی سیتی'],
            ['area_name_en' => 'Aza', 'area_name_ar' => 'عزة', 'area_name_ku' => 'عەزە'],
            ['area_name_en' => 'Azadi', 'area_name_ar' => 'آزادي', 'area_name_ku' => 'ئازادی'],
            ['area_name_en' => 'Azadi 2', 'area_name_ar' => 'آزادي 2', 'area_name_ku' => 'ئازادی 2'],
            ['area_name_en' => 'Azadi Nwe', 'area_name_ar' => 'آزادي نوي', 'area_name_ku' => 'ئازادی نوێ'],
            ['area_name_en' => 'Babagorgor', 'area_name_ar' => 'بابا كوركور', 'area_name_ku' => 'بابەگوڕگوڕ'],
            ['area_name_en' => 'Badawa', 'area_name_ar' => 'باداوا', 'area_name_ku' => 'باداوا'],
            ['area_name_en' => 'Bagh Alminara', 'area_name_ar' => 'باغ المينارة', 'area_name_ku' => 'باغ ئەلمینارە'],
            ['area_name_en' => 'Bahar 1', 'area_name_ar' => 'بھار 1', 'area_name_ku' => 'بەھار 1'],
            ['area_name_en' => 'Bahar 2', 'area_name_ar' => 'بھار 2', 'area_name_ku' => 'بەھار 2'],
            ['area_name_en' => 'Bahari Kon', 'area_name_ar' => 'بھاری كون', 'area_name_ku' => 'بەھاری کۆن'],
            ['area_name_en' => 'Bahari Nwe', 'area_name_ar' => 'بھاری نوي', 'area_name_ku' => 'بەھاری نوێ'],
            ['area_name_en' => 'Bahrka Road', 'area_name_ar' => 'بحرکة', 'area_name_ku' => 'بەحرکە'],
            ['area_name_en' => 'Bakhtyari', 'area_name_ar' => 'بختياري', 'area_name_ku' => 'بەختیاری'],
            ['area_name_en' => 'Barzani Namr Road', 'area_name_ar' => 'طريق بارزاني نمر', 'area_name_ku' => 'شەقامی بارزانی نەمر'],
            ['area_name_en' => 'Bazar', 'area_name_ar' => 'بازار', 'area_name_ku' => 'بازاڕ'],
            ['area_name_en' => 'Behirke', 'area_name_ar' => 'بحيركة', 'area_name_ku' => 'بەحرکە'],
            ['area_name_en' => 'Beribat', 'area_name_ar' => 'بيريبات', 'area_name_ku' => 'بێریبات'],
            ['area_name_en' => 'Berkot', 'area_name_ar' => 'بيركوت', 'area_name_ku' => 'بێرکۆت'],
            ['area_name_en' => 'Biaban', 'area_name_ar' => 'بیابان', 'area_name_ku' => 'بیابان'],
            ['area_name_en' => 'Bnaslawa', 'area_name_ar' => 'بنسلاوة', 'area_name_ku' => 'بنەسڵاوە'],
            ['area_name_en' => 'Bnaslawa Old Road', 'area_name_ar' => 'طريق بنسلاوة القديم', 'area_name_ku' => 'ڕێگای کۆن بنەسڵاوە'],
            ['area_name_en' => 'Brayati', 'area_name_ar' => 'برايتي', 'area_name_ku' => 'برايەتی'],
            ['area_name_en' => 'Chnar', 'area_name_ar' => 'جنار', 'area_name_ku' => 'چنار'],
            ['area_name_en' => 'Chnin', 'area_name_ar' => 'جنين', 'area_name_ku' => 'چنين'],
            ['area_name_en' => 'Chwarchra 2', 'area_name_ar' => 'جوارجرا 2', 'area_name_ku' => 'چوارچرا 2'],
            ['area_name_en' => 'Chwarchra 4', 'area_name_ar' => 'جوارجرا 4', 'area_name_ku' => 'چوارچرا 4'],
            ['area_name_en' => 'Daratu', 'area_name_ar' => 'دارتو', 'area_name_ku' => 'دارەتوو'],
            ['area_name_en' => 'Downtown Erbil', 'area_name_ar' => 'وسط أربيل', 'area_name_ku' => 'ناوەندی هەولێر'],
            ['area_name_en' => 'Dream City', 'area_name_ar' => 'مدينة الأحلام', 'area_name_ku' => 'شاری خەون'],
            ['area_name_en' => 'Dubai City', 'area_name_ar' => 'دوبي سيتي', 'area_name_ku' => 'دوبەی سیتی'],
            ['area_name_en' => 'Empire', 'area_name_ar' => 'إمباير', 'area_name_ku' => 'ئیمپایر'],
            ['area_name_en' => 'English City', 'area_name_ar' => 'إنكليزي سيتي', 'area_name_ku' => 'ئینگلیزی سیتی'],
            ['area_name_en' => 'Falcon City', 'area_name_ar' => 'مدينة الصقور', 'area_name_ku' => 'شاری باڵندە'],
            ['area_name_en' => 'Farmanbaran', 'area_name_ar' => 'فةرمانبةران', 'area_name_ku' => 'فەرمانبەران'],
            ['area_name_en' => 'Floria City', 'area_name_ar' => 'فلوريا سيتي', 'area_name_ku' => 'فلۆریا سیتی'],
            ['area_name_en' => 'Future City', 'area_name_ar' => 'فيوتجر سيتي', 'area_name_ku' => 'فیوچر سیتی'],
            ['area_name_en' => 'Galawezh', 'area_name_ar' => 'كلاويز', 'area_name_ku' => 'گەلاوێژ'],
            ['area_name_en' => 'Galawezh 3', 'area_name_ar' => 'كلاويز 3', 'area_name_ku' => 'گەلاوێژ 3'],
            ['area_name_en' => 'Galawezh 4', 'area_name_ar' => 'كلاويز 4', 'area_name_ku' => 'گەلاوێژ 4'],
            ['area_name_en' => 'Ganjan City', 'area_name_ar' => 'مدينة كنجان', 'area_name_ku' => 'شاری گەنجان'],
            ['area_name_en' => 'Garmyan', 'area_name_ar' => 'گرميان', 'area_name_ku' => 'گەرمیان'],
            ['area_name_en' => 'Gerd Jutyar', 'area_name_ar' => 'كرد جوتیار', 'area_name_ku' => 'گرد جوتیار'],
            ['area_name_en' => 'Goristani Bakur', 'area_name_ar' => 'كورستاني باكور', 'area_name_ku' => 'گۆڕستانی باکوور'],
            ['area_name_en' => 'Goristani Bashur', 'area_name_ar' => 'كورستاني باشو', 'area_name_ku' => 'گۆڕستانی باشوور'],
            ['area_name_en' => 'Grda Rashai Bchuk', 'area_name_ar' => 'كردةرشةي بجوك', 'area_name_ku' => 'گردەڕەشەی بچووک'],
            ['area_name_en' => 'Grda Rashai Gawra', 'area_name_ar' => 'كردةرشةي كةورة', 'area_name_ku' => 'گردەڕەشەی گەورە'],
            ['area_name_en' => 'Gulan', 'area_name_ar' => 'کولان', 'area_name_ku' => 'گوڵان'],
            ['area_name_en' => 'Gulan 1', 'area_name_ar' => 'کولان 1', 'area_name_ku' => 'گوڵان 1'],
            ['area_name_en' => 'Gulan 2', 'area_name_ar' => 'کولان 2', 'area_name_ku' => 'گوڵان 2'],
            ['area_name_en' => 'Gulan 3', 'area_name_ar' => 'کولان 3', 'area_name_ku' => 'گوڵان 3'],
            ['area_name_en' => 'Hamrin', 'area_name_ar' => 'حمرين', 'area_name_ku' => 'حەمرین'],
            ['area_name_en' => 'Hana City', 'area_name_ar' => 'هانا سيتي', 'area_name_ku' => 'هانا سیتی'],
            ['area_name_en' => 'Harshem 1', 'area_name_ar' => 'هرشم 1', 'area_name_ku' => 'هەرشەم 1'],
            ['area_name_en' => 'Havalan', 'area_name_ar' => 'هةفالان', 'area_name_ku' => 'ھەڤاڵان'],
            ['area_name_en' => 'Hawler new', 'area_name_ar' => 'هولير نوی', 'area_name_ku' => 'هەولێری نوێ'],
            ['area_name_en' => 'Hawler new 4', 'area_name_ar' => 'هولير نوی 4', 'area_name_ku' => 'هەولێری نوێ 4'],
            ['area_name_en' => 'Hiwa 1', 'area_name_ar' => 'هیوا 1', 'area_name_ku' => 'هیوا 1'],
            ['area_name_en' => 'Hiwa City 1', 'area_name_ar' => 'هیوا سيتي 1', 'area_name_ku' => 'هیوا سیتی 1'],
            ['area_name_en' => 'Hiwa City 2', 'area_name_ar' => 'هیوا سيتي 2', 'area_name_ku' => 'هیوا سیتی 2'],
            ['area_name_en' => 'Iskan', 'area_name_ar' => 'الإسكان', 'area_name_ku' => 'ئیسکان'],
            ['area_name_en' => 'Italian Village', 'area_name_ar' => 'القرية الإيطالية', 'area_name_ku' => 'گوندی ئیتالی'],
            ['area_name_en' => 'Italian Village 2', 'area_name_ar' => 'القرية الإيطالية 2', 'area_name_ku' => 'گوندی ئیتالی 2'],
            ['area_name_en' => 'jawharawa', 'area_name_ar' => 'جوھةراوة', 'area_name_ku' => 'جەوھەراوە'],
            ['area_name_en' => 'Kalekin', 'area_name_ar' => 'كالاكين', 'area_name_ku' => 'کەلەکین'],
            ['area_name_en' => 'Kamaran City', 'area_name_ar' => 'كامران سيتي', 'area_name_ku' => 'کامەران سیتی'],
            ['area_name_en' => 'Kani', 'area_name_ar' => 'كاني', 'area_name_ku' => 'کانی'],
            ['area_name_en' => 'Karezan 1', 'area_name_ar' => 'کاريزان 1', 'area_name_ku' => 'کارێزان 1'],
            ['area_name_en' => 'Karezan 2', 'area_name_ar' => 'کاريزان 2', 'area_name_ku' => 'کارێزان 2'],
            ['area_name_en' => 'Karezan 3', 'area_name_ar' => 'کاريزان 3', 'area_name_ku' => 'کارێزان 3'],
            ['area_name_en' => 'Karki Gawra', 'area_name_ar' => 'كركي كورة', 'area_name_ku' => 'کەڕکی گەورە'],
            ['area_name_en' => 'Kasnazan', 'area_name_ar' => 'كسنزان', 'area_name_ku' => 'کەسنەزان'],
            ['area_name_en' => 'Khabat', 'area_name_ar' => 'خبات', 'area_name_ku' => 'خەبات'],
            ['area_name_en' => 'Khanaqa', 'area_name_ar' => 'خانقاه', 'area_name_ku' => 'خانەقا'],
            ['area_name_en' => 'Khanzad', 'area_name_ar' => 'خانزاد', 'area_name_ku' => 'خانزاد'],
            ['area_name_en' => 'Khanzad 2', 'area_name_ar' => 'خانزاد 2', 'area_name_ku' => 'خانزاد 2'],
            ['area_name_en' => 'Kirkuk Old Road', 'area_name_ar' => 'طريق كركوك القديم', 'area_name_ku' => 'ڕێگای کۆنی کەرکووک'],
            ['area_name_en' => 'Kirkuk Road', 'area_name_ar' => 'طريق كركوك', 'area_name_ku' => 'ڕێگای کەرکووک'],
            ['area_name_en' => 'Komari', 'area_name_ar' => 'كوماري', 'area_name_ku' => 'کۆماری'],
            ['area_name_en' => 'Kore City', 'area_name_ar' => 'كوري سيتي', 'area_name_ku' => 'کۆری سیتی'],
            ['area_name_en' => 'Koya Road', 'area_name_ar' => 'طريق كوية', 'area_name_ku' => 'ڕێگای کۆیە'],
            ['area_name_en' => 'krd Mohammed', 'area_name_ar' => 'کرد محمد', 'area_name_ku' => 'کرد محەمەد'],
            ['area_name_en' => 'Krekaran', 'area_name_ar' => 'کريکاران', 'area_name_ku' => 'کرێکاران'],
            ['area_name_en' => 'Kuran', 'area_name_ar' => 'کوران', 'area_name_ku' => 'کوران'],
            ['area_name_en' => 'Kurani Nwe', 'area_name_ar' => 'كوراني نو', 'area_name_ku' => 'کورانی نوێ'],
            ['area_name_en' => 'Kurany ankawa', 'area_name_ar' => 'كوراني عةنكاوة', 'area_name_ku' => 'کورانی عەنکاوە'],
            ['area_name_en' => 'Kurdistan', 'area_name_ar' => 'كردستان', 'area_name_ku' => 'کوردستان'],
            ['area_name_en' => 'Kurdistan 2', 'area_name_ar' => 'كردستان 2', 'area_name_ku' => 'کوردستان 2'],
            ['area_name_en' => 'Kurdistan 3', 'area_name_ar' => 'کردستان 3', 'area_name_ku' => 'کوردستان 3'],
            ['area_name_en' => 'Kurdistan City', 'area_name_ar' => 'كردستان سيتي', 'area_name_ku' => 'کوردستان سیتی'],
            ['area_name_en' => 'Kwestan', 'area_name_ar' => 'كويستان', 'area_name_ku' => 'کوێستان'],
            ['area_name_en' => 'Lalav Airport Tower', 'area_name_ar' => 'لالاف إيربورت تاور', 'area_name_ku' => 'لالاڤ ئێرپۆرت تاوەر'],
            ['area_name_en' => 'Lalav City', 'area_name_ar' => 'لالاف سيتي', 'area_name_ku' => 'لالاڤ سیتی'],
            ['area_name_en' => 'Latifawa', 'area_name_ar' => 'لتیفاوة', 'area_name_ku' => 'لەتیفاوە'],
            ['area_name_en' => 'Lubnani City', 'area_name_ar' => 'مدينة لبناني', 'area_name_ku' => 'شاری لوبنان'],
            ['area_name_en' => 'Mahabad', 'area_name_ar' => 'مهاباد', 'area_name_ku' => 'مەهاباد'],
            ['area_name_en' => 'Majidawa', 'area_name_ar' => 'ماجيداوة', 'area_name_ku' => 'ماجیداوە'],
            ['area_name_en' => 'Mala Afandi', 'area_name_ar' => 'ملا أفندي', 'area_name_ku' => 'مالا ئەفەندی'],
            ['area_name_en' => 'Mamostayan 1', 'area_name_ar' => 'ماموستايان 1', 'area_name_ku' => 'مامۆستایان 1'],
            ['area_name_en' => 'Mamostayan 2', 'area_name_ar' => 'ماموستايان 2', 'area_name_ku' => 'مامۆستایان 2'],
            ['area_name_en' => 'Mamostayan City', 'area_name_ar' => 'ماموستايان سيتي', 'area_name_ku' => 'مامۆستایان سیتی'],
            ['area_name_en' => 'Mamzawa', 'area_name_ar' => 'مامزاوة', 'area_name_ku' => 'مامزاوە'],
            ['area_name_en' => 'Mamzawa 1', 'area_name_ar' => 'مامزاوة 1', 'area_name_ku' => 'مامزاوە 1'],
            ['area_name_en' => 'Mamzawa 2', 'area_name_ar' => 'مامزاوة 2', 'area_name_ku' => 'مامزاوە 2'],
            ['area_name_en' => 'Mamzawa 3', 'area_name_ar' => 'مامزاوة 3', 'area_name_ku' => 'مامزاوە 3'],
            ['area_name_en' => 'Mamzawa 4', 'area_name_ar' => 'مامزاوة 4', 'area_name_ku' => 'مامزاوە 4'],
            ['area_name_en' => 'Mar Qardakh street', 'area_name_ar' => 'شارع مار قرداخ', 'area_name_ku' => 'شەقامی مار قارداخ'],
            ['area_name_en' => 'Mardin', 'area_name_ar' => 'ماردين', 'area_name_ku' => 'ماردين'],
            ['area_name_en' => 'Marina 2', 'area_name_ar' => 'مارينا 2', 'area_name_ku' => 'مارینا 2'],
            ['area_name_en' => 'Masif', 'area_name_ar' => 'ماسيف', 'area_name_ku' => 'ماسيف'],
            ['area_name_en' => 'Mass City', 'area_name_ar' => 'ماس سيتي', 'area_name_ku' => 'ماس سیتی'],
            ['area_name_en' => 'Media City', 'area_name_ar' => 'ميديا سيتي', 'area_name_ku' => 'میدیا سیتی'],
            ['area_name_en' => 'Mestawefi', 'area_name_ar' => 'مستوفي', 'area_name_ku' => 'مستەوفی'],
            ['area_name_en' => 'Mezahmed', 'area_name_ar' => 'مزحمد', 'area_name_ku' => 'مزەحمەد'],
            ['area_name_en' => 'Minara', 'area_name_ar' => 'مينارا', 'area_name_ku' => 'مینارە'],
            ['area_name_en' => 'Mnara', 'area_name_ar' => 'منارة', 'area_name_ku' => 'منارە'],
            ['area_name_en' => 'Mnara City', 'area_name_ar' => 'منارة سيتي', 'area_name_ku' => 'منارە سیتی'],
            ['area_name_en' => 'Mntkawa', 'area_name_ar' => 'منتكاوة', 'area_name_ku' => 'مەنتکاوە'],
            ['area_name_en' => 'Mosul Road', 'area_name_ar' => 'طريق الموصل', 'area_name_ku' => 'ڕێگای مووسڵ'],
            ['area_name_en' => 'Mufti', 'area_name_ar' => 'مفتي', 'area_name_ku' => 'موفتی'],
            ['area_name_en' => 'Mz Ahmed', 'area_name_ar' => 'مز احمد', 'area_name_ku' => 'مز ئەحمەد'],
            ['area_name_en' => 'Nawroz 2', 'area_name_ar' => 'نوروز 2', 'area_name_ku' => 'نەورۆز 2'],
            ['area_name_en' => 'Nawroz 3', 'area_name_ar' => 'نوروز 3', 'area_name_ku' => 'نەورۆز 3'],
            ['area_name_en' => 'Naz City', 'area_name_ar' => 'مدينة ناز', 'area_name_ku' => 'ناز سیتی'],
            ['area_name_en' => 'Naz Naz', 'area_name_ar' => 'ناز ناز', 'area_name_ku' => 'ناز ناز'],
            ['area_name_en' => 'Nazmawa', 'area_name_ar' => 'نازماوة', 'area_name_ku' => 'نازماوە'],
            ['area_name_en' => 'Nergz', 'area_name_ar' => 'نرجز', 'area_name_ku' => 'نێرگز'],
            ['area_name_en' => 'Newroz', 'area_name_ar' => 'نوروز', 'area_name_ku' => 'نەورۆز'],
            ['area_name_en' => 'Nishtiman', 'area_name_ar' => 'نيشتيمان', 'area_name_ku' => 'نيشتيمان'],
            ['area_name_en' => 'Nobel', 'area_name_ar' => 'نوبل', 'area_name_ku' => 'نۆبڵ'],
            ['area_name_en' => 'Nusaran', 'area_name_ar' => 'نوسران', 'area_name_ku' => 'نووسەران'],
            ['area_name_en' => 'Pang', 'area_name_ar' => 'بانک', 'area_name_ku' => 'پانگ'],
            ['area_name_en' => 'Parki Shaheed Sami', 'area_name_ar' => 'باركي شهيد سامي', 'area_name_ku' => 'پارکی شەهید سامی'],
            ['area_name_en' => 'Parlaman', 'area_name_ar' => 'برلمان', 'area_name_ku' => 'پەرلەمان'],
            ['area_name_en' => 'Peshawa Qazi', 'area_name_ar' => 'بيشوا قاضي', 'area_name_ku' => 'پێشەوا قازی'],
            ['area_name_en' => 'Pirmam Read', 'area_name_ar' => 'طريق بيرمام', 'area_name_ku' => 'ڕێگای پیرمام'],
            ['area_name_en' => 'Pirzin', 'area_name_ar' => 'بيرزين', 'area_name_ku' => 'پیرزین'],
            ['area_name_en' => 'Pishasazi', 'area_name_ar' => 'بیشةسازی', 'area_name_ku' => 'پیشەسازی'],
            ['area_name_en' => 'Pishasazi Bashur 1', 'area_name_ar' => 'بيشاسازي باشور 1', 'area_name_ku' => 'پیشەسازی باشوور 1'],
            ['area_name_en' => 'Pishasazi Bashur 2', 'area_name_ar' => 'بيشاسازي باشور 2', 'area_name_ku' => 'پیشەسازی باشوور 2'],
            ['area_name_en' => 'Pzhishkan Street', 'area_name_ar' => 'شارع بزشكان', 'area_name_ku' => 'شەقامی پزیشکان'],
            ['area_name_en' => 'Qala Street', 'area_name_ar' => 'شارع القلعة', 'area_name_ku' => 'شەقامی قەڵا'],
            ['area_name_en' => 'Qalat', 'area_name_ar' => 'قلات', 'area_name_ku' => 'قەڵات'],
            ['area_name_en' => 'Qatwi', 'area_name_ar' => 'قتوي', 'area_name_ku' => 'قەتوی'],
            ['area_name_en' => 'Qatwi 2', 'area_name_ar' => 'قتوي 2', 'area_name_ku' => 'قەتوی 2'],
            ['area_name_en' => 'Qatwi 3', 'area_name_ar' => 'قتوي 3', 'area_name_ku' => 'قەتوی 3'],
            ['area_name_en' => 'Rangin', 'area_name_ar' => 'رنگين', 'area_name_ku' => 'رەنگین'],
            ['area_name_en' => 'Raparin', 'area_name_ar' => 'رابةرين', 'area_name_ku' => 'ڕاپەڕین'],
            ['area_name_en' => 'Rashkin', 'area_name_ar' => 'رشكين', 'area_name_ku' => 'ڕەشکین'],
            ['area_name_en' => 'Rasti 1', 'area_name_ar' => 'راستي 1', 'area_name_ku' => 'ڕاستی 1'],
            ['area_name_en' => 'Rasti City 2', 'area_name_ar' => 'راستي سيتي 2', 'area_name_ku' => 'ڕاستی سیتی 2'],
            ['area_name_en' => 'Roman City', 'area_name_ar' => 'مدينة رومان', 'area_name_ku' => 'شاری رۆمان'],
            ['area_name_en' => 'Roshnbiri 2', 'area_name_ar' => 'روشنبيري 2', 'area_name_ku' => 'ڕۆشنبیری 2'],
            ['area_name_en' => 'Roshnbiri 3', 'area_name_ar' => 'روشنبيري 3', 'area_name_ku' => 'ڕۆشنبیری 3'],
            ['area_name_en' => 'Roshnbiri 1', 'area_name_ar' => 'روشنبيري 1', 'area_name_ku' => 'ڕۆشنبیری 1'],
            ['area_name_en' => 'Royal City', 'area_name_ar' => 'المدينة الملكية', 'area_name_ku' => 'شاری شاهانە'],
            ['area_name_en' => 'Rozhava road', 'area_name_ar' => 'شارع روجافا', 'area_name_ku' => 'شەقامی ڕۆژئاوا'],
            ['area_name_en' => 'Runaki Road', 'area_name_ar' => 'طريق روناکي', 'area_name_ku' => 'شەقامی روناکی'],
            ['area_name_en' => 'Rzgari 1', 'area_name_ar' => 'رزكاري 1', 'area_name_ku' => 'رزگاری 1'],
            ['area_name_en' => 'Rzgari 2', 'area_name_ar' => 'رزكاري 2', 'area_name_ku' => 'رزگاری 2'],
            ['area_name_en' => 'Safeen 1', 'area_name_ar' => 'سفين 1', 'area_name_ku' => 'سەفین 1'],
            ['area_name_en' => 'Safeen 2', 'area_name_ar' => 'سفين 2', 'area_name_ku' => 'سەفین 2'],
            ['area_name_en' => 'Safeen 3', 'area_name_ar' => 'سفين 3', 'area_name_ku' => 'سەفین 3'],
            ['area_name_en' => 'Safeen Road', 'area_name_ar' => 'طريق سفين', 'area_name_ku' => 'شەقامی سەفین'],
            ['area_name_en' => 'Saidawa', 'area_name_ar' => 'سيداوە', 'area_name_ku' => 'سەیداوە'],
            ['area_name_en' => 'Sailo', 'area_name_ar' => 'سايلو', 'area_name_ku' => 'سايلۆ'],
            ['area_name_en' => 'Salahaddin 1', 'area_name_ar' => 'صلاح الدين 1', 'area_name_ku' => 'سەلاحەدین 1'],
            ['area_name_en' => 'Salahaddin 2', 'area_name_ar' => 'صلاح الدين 2', 'area_name_ku' => 'سەلاحەدین 2'],
            ['area_name_en' => 'Sana City', 'area_name_ar' => 'سانا سیتی', 'area_name_ku' => 'سانا سیتی'],
            ['area_name_en' => 'Sarbasti', 'area_name_ar' => 'سربستي', 'area_name_ku' => 'سەربەستی'],
            ['area_name_en' => 'Sarbasti 2', 'area_name_ar' => 'سربستي 2', 'area_name_ku' => 'سەربەستی 2'],
            ['area_name_en' => 'Sarbaxoee', 'area_name_ar' => 'سربخویي', 'area_name_ku' => 'سەربەخۆیی'],
            ['area_name_en' => 'Sardar', 'area_name_ar' => 'سردار', 'area_name_ku' => 'سەردار'],
            ['area_name_en' => 'Sarkarez', 'area_name_ar' => 'سركاريز', 'area_name_ku' => 'سەرکارێز'],
            ['area_name_en' => 'Sarwaran', 'area_name_ar' => 'سروران', 'area_name_ku' => 'سەروەران'],
            ['area_name_en' => 'Sebardan', 'area_name_ar' => 'سيبردان', 'area_name_ku' => 'سێبەردان'],
            ['area_name_en' => 'Sebiran', 'area_name_ar' => 'سبيران', 'area_name_ku' => 'سێبیران'],
            ['area_name_en' => 'Setaqan', 'area_name_ar' => 'سیتاقان', 'area_name_ku' => 'سێتاقان'],
            ['area_name_en' => 'Shadi', 'area_name_ar' => 'شادي', 'area_name_ku' => 'شادى'],
            ['area_name_en' => 'Shadi 2', 'area_name_ar' => 'شادي 2', 'area_name_ku' => 'شادى 2'],
            ['area_name_en' => 'Shahidan', 'area_name_ar' => 'شهيدان', 'area_name_ku' => 'شەھیدان'],
            ['area_name_en' => 'Shahidan u Farmanbaran', 'area_name_ar' => 'شهيدان و فةرمانبةران', 'area_name_ku' => 'شەھیدان و فەرمانبەران'],
            ['area_name_en' => 'Shamamek', 'area_name_ar' => 'شمامك', 'area_name_ku' => 'شامامەک'],
            ['area_name_en' => 'Sharawani', 'area_name_ar' => 'شارواني', 'area_name_ku' => 'شاروانی'],
            ['area_name_en' => 'Shari Parezaran', 'area_name_ar' => 'شاري بارێزاران', 'area_name_ku' => 'شاری پارێزەران'],
            ['area_name_en' => 'Shaways', 'area_name_ar' => 'شاويس', 'area_name_ku' => 'شاویس'],
            ['area_name_en' => 'Shorsh', 'area_name_ar' => 'شورش', 'area_name_ku' => 'شۆڕش'],
            ['area_name_en' => 'slava city', 'area_name_ar' => 'سلافا سيتي', 'area_name_ku' => 'سلاڤا سیتی'],
            ['area_name_en' => 'Solav City', 'area_name_ar' => 'سولاف سيتي', 'area_name_ku' => 'سۆلاڤ سیتی'],
            ['area_name_en' => 'Spanish City 1', 'area_name_ar' => 'إسباني سيتي 1', 'area_name_ku' => 'ئیسپانی سیتی 1'],
            ['area_name_en' => 'Spanish City 2', 'area_name_ar' => 'إسباني سيتي 2', 'area_name_ku' => 'ئیسپانی سیتی 2'],
            ['area_name_en' => 'Swery Bchuk', 'area_name_ar' => 'سويري بجوك', 'area_name_ku' => 'سوێری بچووک'],
            ['area_name_en' => 'Swery Gawra', 'area_name_ar' => 'سويري كورة', 'area_name_ku' => 'سوێری گەورە'],
            ['area_name_en' => 'Tahjil', 'area_name_ar' => 'تعجيل', 'area_name_ku' => 'تەعجیل'],
            ['area_name_en' => 'Talar City', 'area_name_ar' => 'تلار سيتي', 'area_name_ku' => 'تەلار سیتی'],
            ['area_name_en' => 'Tayrawa', 'area_name_ar' => 'تيراوە', 'area_name_ku' => 'تەیراوە'],
            ['area_name_en' => 'Timar', 'area_name_ar' => 'تيمار', 'area_name_ku' => 'تيمار'],
            ['area_name_en' => 'Tobzawi Ahmad', 'area_name_ar' => 'توبزاوي احمد', 'area_name_ku' => 'تۆبزاوەی ئەحمەد'],
            ['area_name_en' => 'Tulseglen City', 'area_name_ar' => 'مدينة تولسغلين', 'area_name_ku' => 'شاری تولسگلین'],
            ['area_name_en' => 'Twraq', 'area_name_ar' => 'تورق', 'area_name_ku' => 'تووڕەق'],
            ['area_name_en' => 'Warin City', 'area_name_ar' => 'وارين سيتي', 'area_name_ku' => 'وەرین سیتی'],
            ['area_name_en' => 'Waziran', 'area_name_ar' => 'وزیریان', 'area_name_ku' => 'وەزیران'],
            ['area_name_en' => 'Zanayan', 'area_name_ar' => 'زانایان', 'area_name_ku' => 'زانایان'],
            ['area_name_en' => 'Zanko 1', 'area_name_ar' => 'زانكو 1', 'area_name_ku' => 'زانکۆ 1'],
            ['area_name_en' => 'Zanko 2', 'area_name_ar' => 'زانكو 2', 'area_name_ku' => 'زانکۆ 2'],
            ['area_name_en' => 'Zanyari', 'area_name_ar' => 'زاناري', 'area_name_ku' => 'زانیاری'],
            ['area_name_en' => 'Zarza', 'area_name_ar' => 'زرزا', 'area_name_ku' => 'زەرزا'],
            ['area_name_en' => 'Zaytwn City', 'area_name_ar' => 'زيتون سيتي', 'area_name_ku' => 'زەیتوون سیتی'],
            ['area_name_en' => 'Zerin City', 'area_name_ar' => 'زيرين سيتي', 'area_name_ku' => 'زێڕین سیتی'],
            ['area_name_en' => 'Zilan', 'area_name_ar' => 'زيلان', 'area_name_ku' => 'زیلان'],
            ['area_name_en' => 'Zilan 2', 'area_name_ar' => '2زیلان', 'area_name_ku' => 'زیلان 2'],
            ['area_name_en' => 'Zilan 3', 'area_name_ar' => 'زیلان 3', 'area_name_ku' => 'زیلان 3'],
            ['area_name_en' => 'Zilan 4', 'area_name_ar' => 'زیلان 4', 'area_name_ku' => 'زیلان 4'],
            ['area_name_en' => 'Zilan 5', 'area_name_ar' => 'زیلان 5', 'area_name_ku' => 'زیلان 5'],
            ['area_name_en' => 'Zilan 6', 'area_name_ar' => 'زیلان 6', 'area_name_ku' => 'زیلان 6'],
            ['area_name_en' => 'Zin City', 'area_name_ar' => 'زين سيتي', 'area_name_ku' => 'زین سیتی'],
        ];

        $count = 0;
        foreach ($areas as $area) {
            $exists = Area::where('branch_id', $erbil->id)
                ->where('area_name_en', $area['area_name_en'])
                ->exists();

            if (!$exists) {
                Area::create(array_merge($area, [
                    'branch_id' => $erbil->id,
                    'is_active' => true,
                ]));
                $count++;
            }
        }

        $this->command->info("✅ Done! {$count} new Erbil areas inserted (duplicates skipped).");
    }
}
