<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

/**
 * PRICE ZONES
 * ─────────────────────────────────────────────────────────────────────────────
 * Stores geospatial clustering results as map zones.
 * Each row = one price zone polygon with its GeoJSON boundary,
 * color code, and summary statistics.
 *
 * Generated by: Python /cluster-zones endpoint → ComputePriceZonesJob
 * Consumed by:  GET /map/zones  (Flutter map polygon rendering)
 *
 * Zone colors:
 *   green  = affordable  (bottom 25th percentile price/m²)
 *   yellow = medium      (25th–60th percentile)
 *   orange = expensive   (60th–85th percentile)
 *   red    = luxury      (85th+ percentile)
 * ─────────────────────────────────────────────────────────────────────────────
 */
return new class extends Migration
{
    public function up(): void
    {
        Schema::create('price_zones', function (Blueprint $table) {

            $table->id();

            // ── Zone identity ─────────────────────────────────────────────────
            $table->string('zone_name', 100);               // e.g. "Erbil Zone A"
            $table->string('zone_code', 20)->unique();      // e.g. "EBL-A-001"

            // ── Tier & color ──────────────────────────────────────────────────
            // tier:  affordable | medium | expensive | luxury
            // color: hex code for Flutter map rendering
            $table->enum('tier', ['affordable', 'medium', 'expensive', 'luxury']);
            $table->string('color_hex', 10)->default('#22C55E'); // green default

            // ── GeoJSON polygon boundary ──────────────────────────────────────
            // Full GeoJSON Feature object stored as JSON.
            // Shape generated by Shapely ConvexHull / alpha shape in Python.
            // Stored as LONGTEXT to support complex polygon boundaries.
            $table->longText('geojson_polygon');

            // ── Bounding box for fast spatial queries ─────────────────────────
            // Allows "which zone does this point fall in?" without parsing GeoJSON
            $table->decimal('bbox_min_lat', 10, 7)->nullable();
            $table->decimal('bbox_max_lat', 10, 7)->nullable();
            $table->decimal('bbox_min_lng', 10, 7)->nullable();
            $table->decimal('bbox_max_lng', 10, 7)->nullable();

            // ── Centroid (zone center point) ──────────────────────────────────
            $table->decimal('centroid_lat', 10, 7)->nullable();
            $table->decimal('centroid_lng', 10, 7)->nullable();

            // ── Zone statistics ───────────────────────────────────────────────
            $table->decimal('avg_price_per_m2',  10, 2)->default(0);
            $table->decimal('min_price_per_m2',  10, 2)->default(0);
            $table->decimal('max_price_per_m2',  10, 2)->default(0);
            $table->decimal('avg_total_price',   15, 2)->default(0);
            $table->unsignedInteger('property_count')->default(0);

            // ── Demand & investment ───────────────────────────────────────────
            $table->decimal('demand_score',    5, 2)->default(0);
            $table->decimal('investment_score', 5, 2)->default(0);

            // ── Clustering metadata ───────────────────────────────────────────
            // algorithm: kmeans | dbscan
            // cluster_id: the original cluster index from Python
            $table->string('algorithm', 20)->default('kmeans');
            $table->unsignedSmallInteger('cluster_id')->default(0);

            // ── Branch (city) reference ───────────────────────────────────────
            // Optional link to existing branches table
            $table->unsignedBigInteger('branch_id')->nullable();
            $table->foreign('branch_id')
                ->references('id')
                ->on('branches')
                ->onDelete('set null');

            // ── Version control ───────────────────────────────────────────────
            // Each re-clustering run gets a new version.
            // Only the latest version is served by the API.
            $table->unsignedSmallInteger('version')->default(1);
            $table->boolean('is_active')->default(true);
            $table->timestamp('computed_at')->nullable();

            $table->timestamps();

            // ── Indexes ───────────────────────────────────────────────────────
            $table->index('tier');
            $table->index('is_active');
            $table->index('branch_id');
            $table->index('version');
            $table->index(['is_active', 'tier']);                // common filter
            $table->index([
                'bbox_min_lat',
                'bbox_max_lat',
                'bbox_min_lng',
                'bbox_max_lng'
            ]);     // spatial bbox
        });
    }

    public function down(): void
    {
        Schema::dropIfExists('price_zones');
    }
};
