<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

/**
 * HEATMAP TILES
 * ─────────────────────────────────────────────────────────────────────────────
 * Pre-computed grid cells for Flutter heatmap layer rendering.
 *
 * The Kurdistan region is divided into a uniform grid.
 * Each cell is approximately 500m × 500m (0.005 degree resolution).
 *
 * Three heatmap types are supported:
 *   - price     : average price density in this cell
 *   - demand    : listing inquiry/view density
 *   - density   : raw listing count density
 *
 * Flutter reads these as weighted points:
 *   { latitude, longitude, weight }  where weight = 0.0 – 1.0
 *
 * Generated by: Python /heatmap endpoint → ComputeHeatmapJob
 * Consumed by:  GET /map/heatmap?type=price|demand|density
 * ─────────────────────────────────────────────────────────────────────────────
 */
return new class extends Migration
{
    public function up(): void
    {
        Schema::create('heatmap_tiles', function (Blueprint $table) {

            $table->id();

            // ── Grid cell coordinates ─────────────────────────────────────────
            // lat/lng of the CENTER point of the grid cell
            $table->decimal('latitude',  10, 7);
            $table->decimal('longitude', 10, 7);

            // ── Grid cell boundaries ──────────────────────────────────────────
            // Used to aggregate properties that fall within this cell
            $table->decimal('cell_min_lat', 10, 7);
            $table->decimal('cell_max_lat', 10, 7);
            $table->decimal('cell_min_lng', 10, 7);
            $table->decimal('cell_max_lng', 10, 7);

            // ── Heatmap type ──────────────────────────────────────────────────
            // Separate rows for each type — allows filtering by type in one query
            $table->enum('heatmap_type', ['price', 'demand', 'density']);

            // ── Weight value (0.0000 – 1.0000) ───────────────────────────────
            // Normalized value used directly by Flutter heatmap widget
            $table->decimal('weight', 6, 4)->default(0);

            // ── Raw values (before normalization) ────────────────────────────
            // Stored for debugging and re-normalization without re-computing
            $table->decimal('raw_value',   15, 2)->default(0);
            $table->unsignedInteger('property_count')->default(0);
            $table->decimal('avg_price',   15, 2)->default(0);
            $table->decimal('avg_price_per_m2', 10, 2)->default(0);

            // ── City reference ────────────────────────────────────────────────
            $table->unsignedBigInteger('branch_id')->nullable();
            $table->foreign('branch_id')
                ->references('id')
                ->on('branches')
                ->onDelete('set null');

            // ── Version & freshness ───────────────────────────────────────────
            $table->unsignedSmallInteger('version')->default(1);
            $table->boolean('is_active')->default(true);
            $table->timestamp('computed_at')->nullable();

            $table->timestamps();

            // ── Indexes ───────────────────────────────────────────────────────
            // Primary query: SELECT * WHERE heatmap_type = ? AND is_active = 1
            $table->index(['heatmap_type', 'is_active']);

            // Spatial bbox query for viewport-based loading
            $table->index([
                'cell_min_lat',
                'cell_max_lat',
                'cell_min_lng',
                'cell_max_lng'
            ]);

            $table->index('branch_id');
            $table->index('weight');

            // Unique per cell+type+version — prevents duplicate tiles
            $table->unique(
                ['latitude', 'longitude', 'heatmap_type', 'version'],
                'unique_tile_per_version'
            );
        });
    }

    public function down(): void
    {
        Schema::dropIfExists('heatmap_tiles');
    }
};
