<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

/**
 * INVESTMENT SCORES
 * ─────────────────────────────────────────────────────────────────────────────
 * Detailed investment scoring breakdown per area.
 * Companion to area_market_insights — separates investment logic
 * so it can be computed independently and at different intervals.
 *
 * Investment Score Formula (0–100):
 *   price_growth_score  (30%) — based on price_growth_90d
 *   demand_score        (25%) — listing views & inquiry velocity
 *   supply_score        (20%) — inverse of listing count (low supply = high score)
 *   liquidity_score     (15%) — speed of transactions
 *   development_score   (10%) — POI density, infrastructure nearby
 *
 * Generated by: ComputeInvestmentScoresJob (weekly)
 * Consumed by:  GET /areas/market-insights/{id} (investment tab)
 * ─────────────────────────────────────────────────────────────────────────────
 */
return new class extends Migration
{
    public function up(): void
    {
        Schema::create('investment_scores', function (Blueprint $table) {

            $table->id();

            // ── Area reference ────────────────────────────────────────────────
            $table->unsignedBigInteger('area_id');
            $table->foreign('area_id')
                ->references('id')
                ->on('areas')
                ->onDelete('cascade');

            // ── Final investment score (0.00 – 100.00) ───────────────────────
            $table->decimal('investment_score', 5, 2)->default(0);

            // ── Score components (each 0.00 – 100.00) ────────────────────────
            // Stored separately so the UI can show a breakdown chart
            $table->decimal('price_growth_score', 5, 2)->default(0);
            $table->decimal('demand_score',       5, 2)->default(0);
            $table->decimal('supply_score',       5, 2)->default(0);
            $table->decimal('liquidity_score',    5, 2)->default(0);
            $table->decimal('development_score',  5, 2)->default(0);

            // ── Weights used (stored for transparency & re-computation) ───────
            $table->decimal('weight_price_growth', 4, 2)->default(0.30);
            $table->decimal('weight_demand',       4, 2)->default(0.25);
            $table->decimal('weight_supply',       4, 2)->default(0.20);
            $table->decimal('weight_liquidity',    4, 2)->default(0.15);
            $table->decimal('weight_development',  4, 2)->default(0.10);

            // ── Grade & recommendation ────────────────────────────────────────
            // grade: A+ | A | B | C | D
            // recommendation: strong_buy | buy | hold | avoid
            $table->string('grade', 5)->default('C');
            $table->enum(
                'recommendation',
                ['strong_buy', 'buy', 'hold', 'avoid']
            )
                ->default('hold');

            // ── Supporting raw metrics (inputs to the score) ──────────────────
            $table->decimal('price_growth_90d',     6, 2)->default(0);
            $table->decimal('listing_velocity',     8, 2)->default(0); // new listings/week
            $table->decimal('avg_days_on_market',   8, 2)->default(0);
            $table->unsignedInteger('poi_count')->default(0);         // nearby POIs
            $table->unsignedInteger('active_listing_count')->default(0);

            // ── Trend direction ───────────────────────────────────────────────
            // rising | stable | declining
            $table->enum('trend', ['rising', 'stable', 'declining'])
                ->default('stable');

            // ── Detailed analysis text ────────────────────────────────────────
            // AI-generated plain-language summary for the Flutter panel
            $table->text('analysis_summary')->nullable();

            // ── Risk flags ────────────────────────────────────────────────────
            // JSON array: e.g. ["high_supply", "price_decline", "low_demand"]
            $table->json('risk_flags')->nullable();

            // ── Positive signals ──────────────────────────────────────────────
            // JSON array: e.g. ["strong_demand", "price_growth", "low_supply"]
            $table->json('positive_signals')->nullable();

            $table->timestamp('computed_at')->nullable();
            $table->timestamps();

            // ── Indexes ───────────────────────────────────────────────────────
            $table->unique('area_id'); // One active score per area
            $table->index('investment_score');
            $table->index('grade');
            $table->index('recommendation');
            $table->index('trend');
        });
    }

    public function down(): void
    {
        Schema::dropIfExists('investment_scores');
    }
};
