<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

/**
 * PROPERTY VALUATIONS
 * ─────────────────────────────────────────────────────────────────────────────
 * Stores AI-predicted fair market valuations per property.
 * One row per property per model version.
 *
 * This table answers: "Is this property fairly priced?"
 *
 * Generated by: Python /predict endpoint
 * Triggered by: ComputePropertyValuationsJob (batch) or
 *               on-demand via GET /properties/ai-valuation/{id}
 *
 * Linked to: properties.id (existing table — NOT modified)
 * ─────────────────────────────────────────────────────────────────────────────
 */
return new class extends Migration
{
    public function up(): void
    {
        Schema::create('property_valuations', function (Blueprint $table) {

            $table->id();

            // ── Property reference ────────────────────────────────────────────
            $table->unsignedBigInteger('property_id');
            $table->foreign('property_id')
                ->references('id')
                ->on('properties')
                ->onDelete('cascade');

            // ── Predicted values ──────────────────────────────────────────────
            $table->decimal('predicted_price',       15, 2);
            $table->decimal('predicted_price_per_m2', 10, 2);

            // ── Actual values at time of prediction (snapshot) ────────────────
            // Stored so we can calculate accuracy later without joining properties
            $table->decimal('actual_price',          15, 2)->nullable();
            $table->decimal('actual_price_per_m2',   10, 2)->nullable();
            $table->decimal('actual_area_m2',         10, 2)->nullable();

            // ── Pricing analysis ──────────────────────────────────────────────
            // overprice_percent  > 0: listed ABOVE predicted (overpriced)
            // underprice_percent > 0: listed BELOW predicted (bargain)
            $table->decimal('overprice_percent',  6, 2)->default(0);
            $table->decimal('underprice_percent', 6, 2)->default(0);

            // ── Price range ───────────────────────────────────────────────────
            // The confidence interval: predicted price ± margin
            $table->decimal('predicted_price_low',  15, 2)->nullable();
            $table->decimal('predicted_price_high', 15, 2)->nullable();

            // ── Confidence score (0.00 – 1.00) ───────────────────────────────
            // 1.0 = very confident, 0.5 = uncertain
            // Based on: comparable listings in area, model RMSE, feature completeness
            $table->decimal('confidence_score', 4, 2)->default(0);

            // ── Valuation verdict ─────────────────────────────────────────────
            // fair_value   : within ±10% of predicted
            // overpriced   : listed > predicted + 10%
            // underpriced  : listed < predicted - 10%
            // great_deal   : listed < predicted - 20%
            $table->enum('verdict', ['fair_value', 'overpriced', 'underpriced', 'great_deal'])
                ->default('fair_value');

            // ── Feature inputs used for prediction ────────────────────────────
            // Stored as JSON snapshot so we know WHAT data the model saw
            $table->json('feature_inputs')->nullable();

            // ── Model metadata ────────────────────────────────────────────────
            $table->string('model_version', 20)->default('v1.0');
            $table->string('algorithm',     30)->default('xgboost');

            // ── Comparables ───────────────────────────────────────────────────
            // JSON array of comparable property IDs used in this valuation
            $table->json('comparable_property_ids')->nullable();

            // ── Status ────────────────────────────────────────────────────────
            // pending: not yet computed, processing: in queue,
            // completed: ready, failed: error
            $table->enum('status', ['pending', 'processing', 'completed', 'failed'])
                ->default('pending');
            $table->text('error_message')->nullable();

            $table->timestamp('predicted_at')->nullable();
            $table->timestamps();

            // ── Indexes ───────────────────────────────────────────────────────
            // Latest valuation per property
            $table->index(['property_id', 'status']);
            $table->index(['property_id', 'model_version']);
            $table->index('verdict');
            $table->index('confidence_score');
            $table->index('predicted_at');

            // Only one active completed valuation per property per model version
            $table->unique(['property_id', 'model_version'], 'unique_valuation_per_version');
        });
    }

    public function down(): void
    {
        Schema::dropIfExists('property_valuations');
    }
};
